#!/usr/bin/env python3
"""Deterministic weighted 3-VM sharding, execution and verified merge.

The shard layer changes no task or simulator input.  It partitions the
canonical unique-simulation IDs generated by the v2.6.1 reference/accelerated
runners.  Weight is the number of integration steps times the number of model
calls required for dynamic/yoked references.  Merge fails closed unless every
canonical simulation appears exactly once and every checkpoint validates.
"""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
import os
from pathlib import Path
import shutil
import tempfile
from typing import Dict, Mapping, Sequence, Tuple

import run_ah_experiments_v2_6_1 as reference
import run_ah_experiments_accelerated_v2_6_1 as accelerated


SHARD_SCHEMA = "weighted-lpt-simulation-shards-v2.6.1"
DEFAULT_SHARD_COUNT = 3
SMOKE_EQUIVALENCE_REPORT = (
    Path(__file__).resolve().parent / "shard_equivalence_v2_6_1.json"
)


def canonical_json_sha256(value: object) -> str:
    payload = json.dumps(
        value, sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def estimated_work_units(task: reference.Task, smoke: bool) -> int:
    cfg = reference.config_for_task(task, smoke)
    integration_steps = int(round(cfg.duration_s * 1000.0 / cfg.dt_ms))
    model_calls = 1
    if task.mt_mode == "time_yoked":
        model_calls += 1
    if task.fast_mode == "yoked":
        model_calls += 1
    return integration_steps * model_calls


def deterministic_lpt_assignment(
    representatives: Mapping[str, reference.Task],
    shard_count: int,
    smoke: bool,
) -> Tuple[Tuple[Dict[str, object], ...], Tuple[int, ...]]:
    if shard_count <= 0:
        raise ValueError("shard_count must be positive")
    jobs = [
        (sid, task, estimated_work_units(task, smoke))
        for sid, task in representatives.items()
    ]
    jobs.sort(key=lambda row: (-row[2], row[0]))
    loads = [0] * shard_count
    rows = []
    for sid, task, weight in jobs:
        shard_index = min(range(shard_count), key=lambda i: (loads[i], i))
        loads[shard_index] += weight
        rows.append({
            "simulation_id": sid,
            "representative_task_id": task.task_id,
            "shard_index": shard_index,
            "estimated_work_units": weight,
        })
    rows.sort(key=lambda row: row["simulation_id"])
    return tuple(rows), tuple(loads)


def build_workload(
    *,
    stages: Sequence[str],
    production: bool,
    explicit_seeds: Sequence[int] = (),
    smoke: bool,
    limit: int | None = None,
):
    tasks = (
        reference.build_production_tasks(stages)
        if production
        else reference.build_tasks(stages, explicit_seeds)
    )
    if limit is not None:
        if limit <= 0:
            raise ValueError("limit must be positive")
        tasks = tasks[:limit]
    representatives, task_to_sim, multiplicity = accelerated.unique_simulations(
        tasks, smoke
    )
    return tasks, representatives, task_to_sim, multiplicity


def build_shard_manifest(
    *,
    shard_count: int,
    stages: Sequence[str] = reference.STAGES,
    production: bool = True,
    explicit_seeds: Sequence[int] = (),
    smoke: bool = False,
    limit: int | None = None,
    production_root: str | None = None,
) -> Dict[str, object]:
    tasks, representatives, _, _ = build_workload(
        stages=stages,
        production=production,
        explicit_seeds=explicit_seeds,
        smoke=smoke,
        limit=limit,
    )
    if production:
        accelerated.assert_production_task_matrix(tasks, representatives)
    assignments, loads = deterministic_lpt_assignment(
        representatives, shard_count, smoke
    )
    counts = Counter(int(row["shard_index"]) for row in assignments)
    assignment_sha = canonical_json_sha256(assignments)
    return {
        "schema": SHARD_SCHEMA,
        "scientific_results": False,
        "model_version": accelerated.EXPECTED_MODEL_VERSION,
        "model_sha256": accelerated.EXPECTED_MODEL_SHA256,
        "accelerated_runner_sha256": accelerated.sha256_file(
            Path(accelerated.__file__).resolve()
        ),
        "reference_runner_sha256": accelerated.sha256_file(
            Path(reference.__file__).resolve()
        ),
        "execution_profile": (
            "scientific_full_resolution" if production else "development"
        ),
        "smoke": smoke,
        "stages": list(stages),
        "explicit_seeds": list(explicit_seeds),
        "limit": limit,
        "production_root": production_root,
        "analysis_task_count": len(tasks),
        "unique_simulation_count": len(representatives),
        "task_identity_sha256": accelerated.task_identity_sha256(tasks),
        "shard_count": shard_count,
        "assignment_algorithm": (
            "deterministic_lpt_by_integration_steps_times_required_model_calls"
        ),
        "shard_estimated_work_units": list(loads),
        "shard_unique_simulation_counts": [
            counts.get(index, 0) for index in range(shard_count)
        ],
        "assignment_sha256": assignment_sha,
        "assignments": list(assignments),
    }


def write_manifest(path: Path, manifest: Mapping[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(manifest, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )


def load_and_verify_manifest(path: Path) -> Dict[str, object]:
    manifest = accelerated.load_json_contract(path, "shard manifest")
    if manifest.get("schema") != SHARD_SCHEMA:
        raise RuntimeError("shard manifest schema mismatch")
    if manifest.get("model_sha256") != accelerated.EXPECTED_MODEL_SHA256:
        raise RuntimeError("shard manifest model SHA mismatch")
    if manifest.get("model_version") != accelerated.EXPECTED_MODEL_VERSION:
        raise RuntimeError("shard manifest model version mismatch")
    if manifest.get("accelerated_runner_sha256") != accelerated.sha256_file(
        Path(accelerated.__file__).resolve()
    ):
        raise RuntimeError("shard manifest accelerated-runner SHA mismatch")
    if manifest.get("reference_runner_sha256") != accelerated.sha256_file(
        Path(reference.__file__).resolve()
    ):
        raise RuntimeError("shard manifest reference-runner SHA mismatch")
    assignments = manifest.get("assignments")
    if not isinstance(assignments, list):
        raise RuntimeError("shard assignments missing")
    if canonical_json_sha256(assignments) != manifest.get("assignment_sha256"):
        raise RuntimeError("shard assignment SHA mismatch")
    ids = [row.get("simulation_id") for row in assignments if isinstance(row, dict)]
    if len(ids) != len(assignments) or len(ids) != len(set(ids)):
        raise RuntimeError("shard assignments are incomplete or duplicated")
    shard_count = int(manifest.get("shard_count", 0))
    if shard_count <= 0 or any(
        not isinstance(row, dict)
        or not 0 <= int(row.get("shard_index", -1)) < shard_count
        for row in assignments
    ):
        raise RuntimeError("shard index outside declared range")
    return manifest


def workload_from_manifest(manifest: Mapping[str, object]):
    production = manifest["execution_profile"] == "scientific_full_resolution"
    return build_workload(
        stages=tuple(str(value) for value in manifest["stages"]),
        production=production,
        explicit_seeds=tuple(int(value) for value in manifest["explicit_seeds"]),
        smoke=bool(manifest["smoke"]),
        limit=(None if manifest["limit"] is None else int(manifest["limit"])),
    )


def verify_assignment_against_workload(
    manifest: Mapping[str, object], representatives: Mapping[str, reference.Task]
) -> None:
    rows = manifest["assignments"]
    by_id = {str(row["simulation_id"]): row for row in rows}
    if set(by_id) != set(representatives):
        raise RuntimeError("shard assignment does not exactly cover canonical workload")
    for sid, task in representatives.items():
        row = by_id[sid]
        if row["representative_task_id"] != task.task_id:
            raise RuntimeError(f"representative task drift for {sid}")
        expected_weight = estimated_work_units(task, bool(manifest["smoke"]))
        if int(row["estimated_work_units"]) != expected_weight:
            raise RuntimeError(f"weight drift for {sid}")


def run_shard(
    manifest_path: Path,
    shard_index: int,
    workers: int,
    progress_every: int,
) -> Dict[str, object]:
    manifest = load_and_verify_manifest(manifest_path)
    tasks, representatives, _, _ = workload_from_manifest(manifest)
    verify_assignment_against_workload(manifest, representatives)
    shard_count = int(manifest["shard_count"])
    if not 0 <= shard_index < shard_count:
        raise ValueError("shard_index outside manifest")
    production = manifest["execution_profile"] == "scientific_full_resolution"
    root_text = manifest.get("production_root")
    if root_text is None:
        raise RuntimeError("shard manifest lacks a common production_root")
    root = Path(str(root_text)).expanduser().resolve()
    if production:
        accelerated.assert_production_release_authorized(smoke=False, dry_run=False)
        accelerated.claim_single_production_run(
            root,
            claim_path=root / "SINGLE_PRODUCTION_RUN_CLAIM_v2_6_1.json",
        )
    output_dir = root / "shards" / f"shard-{shard_index:03d}"
    output_dir.mkdir(parents=True, exist_ok=True)
    assigned_ids = {
        str(row["simulation_id"])
        for row in manifest["assignments"]
        if int(row["shard_index"]) == shard_index
    }
    completed = accelerated.existing_simulations(output_dir)
    pending = [
        (sid, representatives[sid])
        for sid in sorted(assigned_ids)
        if sid not in completed
    ]
    durations = accelerated.run_pending_parallel(
        pending,
        output_dir,
        bool(manifest["smoke"]),
        False,
        workers,
        progress_every,
    )
    final_ids = accelerated.existing_simulations(output_dir)
    if final_ids != assigned_ids:
        raise RuntimeError("shard completion set is not exact")
    report = {
        "schema": "v2.6.1-shard-completion",
        "shard_manifest_sha256": accelerated.sha256_file(manifest_path),
        "assignment_sha256": manifest["assignment_sha256"],
        "shard_index": shard_index,
        "shard_count": shard_count,
        "assigned_simulation_count": len(assigned_ids),
        "completed_simulation_count": len(final_ids),
        "elapsed_worker_seconds_sum": float(sum(durations)),
        "passes": True,
    }
    write_manifest(output_dir / "shard_completion.json", report)
    return report


def _link_or_copy(source: Path, destination: Path) -> None:
    if destination.exists():
        if source.read_bytes() != destination.read_bytes():
            raise RuntimeError(f"merge collision differs: {destination.name}")
        return
    try:
        os.link(source, destination)
    except OSError:
        shutil.copy2(source, destination)


def merge_shards(manifest_path: Path, workers: int) -> Dict[str, object]:
    manifest = load_and_verify_manifest(manifest_path)
    tasks, representatives, task_to_sim, multiplicity = workload_from_manifest(
        manifest
    )
    verify_assignment_against_workload(manifest, representatives)
    root_text = manifest.get("production_root")
    if root_text is None:
        raise RuntimeError("shard manifest lacks production_root")
    root = Path(str(root_text)).expanduser().resolve()
    production = manifest["execution_profile"] == "scientific_full_resolution"
    authorization = None
    if production:
        accelerated.assert_production_release_authorized(smoke=False, dry_run=False)
        authorization = accelerated.claim_single_production_run(
            root,
            claim_path=root / "SINGLE_PRODUCTION_RUN_CLAIM_v2_6_1.json",
        )
    merged_dir = root / "simulations"
    merged_dir.mkdir(parents=True, exist_ok=True)
    observed = set()
    for index in range(int(manifest["shard_count"])):
        shard_dir = root / "shards" / f"shard-{index:03d}"
        completion = accelerated.load_json_contract(
            shard_dir / "shard_completion.json", f"shard {index} completion"
        )
        if completion.get("passes") is not True:
            raise RuntimeError(f"shard {index} did not pass")
        if completion.get("assignment_sha256") != manifest["assignment_sha256"]:
            raise RuntimeError(f"shard {index} assignment identity drift")
        assigned = {
            str(row["simulation_id"])
            for row in manifest["assignments"]
            if int(row["shard_index"]) == index
        }
        actual = accelerated.existing_simulations(shard_dir)
        if actual != assigned:
            raise RuntimeError(f"shard {index} checkpoint set is not exact")
        if observed & actual:
            raise RuntimeError("a simulation was produced by more than one shard")
        observed.update(actual)
        for sid in sorted(actual):
            source = shard_dir / "simulations" / f"{sid}.json"
            destination = merged_dir / source.name
            accelerated.validate_checkpoint(source, sid)
            _link_or_copy(source, destination)
            accelerated.validate_checkpoint(destination, sid)
    if observed != set(representatives):
        raise RuntimeError("merged shards do not cover the canonical workload")
    seed_values = tuple(sorted({task.seed for task in tasks}))
    accelerated.write_execution_plan(
        root,
        tasks,
        tuple(str(value) for value in manifest["stages"]),
        seed_values,
        "production_split" if production else "explicit",
        bool(manifest["smoke"]),
        workers,
        representatives,
        task_to_sim,
        multiplicity,
        authorization,
    )
    accelerated.write_task_index(root, tasks, task_to_sim, multiplicity)
    accelerated.compile_outputs(root, tasks, task_to_sim, multiplicity)
    report = {
        "schema": "v2.6.1-verified-shard-merge",
        "shard_manifest_sha256": accelerated.sha256_file(manifest_path),
        "assignment_sha256": manifest["assignment_sha256"],
        "merged_unique_simulation_count": len(observed),
        "expected_unique_simulation_count": len(representatives),
        "analysis_task_count": len(tasks),
        "task_identity_sha256": accelerated.task_identity_sha256(tasks),
        "passes": True,
    }
    write_manifest(root / "shard_merge_report.json", report)
    return report


def smoke_equivalence() -> Dict[str, object]:
    tasks, representatives, task_to_sim, multiplicity = build_workload(
        stages=("A",),
        production=False,
        explicit_seeds=(9001,),
        smoke=True,
        limit=3,
    )
    assignments, loads = deterministic_lpt_assignment(
        representatives, DEFAULT_SHARD_COUNT, True
    )
    with tempfile.TemporaryDirectory(prefix="v261-shard-equivalence-") as temp:
        base = Path(temp)
        single = base / "single"
        single.mkdir()
        accelerated.run_pending_parallel(
            sorted(representatives.items()), single, True, False, 3, 1
        )
        shard_root = base / "sharded"
        for index in range(DEFAULT_SHARD_COUNT):
            out = shard_root / "shards" / f"shard-{index:03d}"
            out.mkdir(parents=True)
            ids = [
                str(row["simulation_id"])
                for row in assignments
                if int(row["shard_index"]) == index
            ]
            accelerated.run_pending_parallel(
                [(sid, representatives[sid]) for sid in ids],
                out,
                True,
                False,
                1,
                1,
            )
        mismatch = []
        seen = set()
        merged = shard_root / "simulations"
        merged.mkdir(parents=True)
        for row in assignments:
            sid = str(row["simulation_id"])
            index = int(row["shard_index"])
            source = shard_root / "shards" / f"shard-{index:03d}" / "simulations" / f"{sid}.json"
            accelerated.validate_checkpoint(source, sid)
            if sid in seen:
                raise RuntimeError("smoke assignment duplicated a simulation")
            seen.add(sid)
            target = merged / source.name
            _link_or_copy(source, target)
            single_bytes = (single / "simulations" / source.name).read_bytes()
            if source.read_bytes() != single_bytes:
                mismatch.append(sid)
        if seen != set(representatives):
            raise RuntimeError("smoke assignment omitted a simulation")
        accelerated.compile_outputs(
            shard_root, tasks, task_to_sim, multiplicity
        )
        report = {
            "scientific_results": False,
            "validation_kind": "single_runner_vs_three_shard_exact_checkpoint_equivalence",
            "analysis_task_count": len(tasks),
            "unique_simulation_count": len(representatives),
            "shard_loads": list(loads),
            "assignment_sha256": canonical_json_sha256(assignments),
            "checkpoint_mismatches": mismatch,
            "exact_checkpoint_equivalence": not mismatch,
            "compiled_metrics_created": (shard_root / "metrics.csv").is_file(),
            "passes": not mismatch and seen == set(representatives),
        }
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    plan = sub.add_parser("plan")
    plan.add_argument("--out", required=True)
    plan.add_argument("--production-root", required=True)
    plan.add_argument("--shards", type=int, default=DEFAULT_SHARD_COUNT)
    run = sub.add_parser("run-shard")
    run.add_argument("--manifest", required=True)
    run.add_argument("--index", type=int, required=True)
    run.add_argument("--workers", type=int, required=True)
    run.add_argument("--progress-every", type=int, default=25)
    merge = sub.add_parser("merge")
    merge.add_argument("--manifest", required=True)
    merge.add_argument("--workers", type=int, required=True)
    sub.add_parser("smoke-equivalence")
    args = parser.parse_args()

    if args.command == "plan":
        manifest = build_shard_manifest(
            shard_count=args.shards,
            production=True,
            production_root=str(Path(args.production_root).expanduser().resolve()),
        )
        output = Path(args.out).expanduser().resolve()
        write_manifest(output, manifest)
        print(json.dumps({
            "manifest": str(output),
            "manifest_sha256": accelerated.sha256_file(output),
            "shard_counts": manifest["shard_unique_simulation_counts"],
            "shard_work_units": manifest["shard_estimated_work_units"],
            "assignment_sha256": manifest["assignment_sha256"],
        }, indent=2))
    elif args.command == "run-shard":
        print(json.dumps(run_shard(
            Path(args.manifest).expanduser().resolve(),
            args.index,
            args.workers,
            args.progress_every,
        ), indent=2))
    elif args.command == "merge":
        print(json.dumps(merge_shards(
            Path(args.manifest).expanduser().resolve(), args.workers
        ), indent=2))
    else:
        report = smoke_equivalence()
        write_manifest(SMOKE_EQUIVALENCE_REPORT, report)
        print(json.dumps({
            **report,
            "report_path": str(SMOKE_EQUIVALENCE_REPORT),
            "report_sha256": accelerated.sha256_file(
                SMOKE_EQUIVALENCE_REPORT
            ),
        }, indent=2))


if __name__ == "__main__":
    main()
